### ISSUE TITLE
Restrict left argument of `Cider.CloseProject` to a flag

### ISSUE THREAD

**Issue by 5jt** [aplteam/Cider#100]
The optional left argument `x` is a flag, a list of projects, or both. The function sets a variable `list` and closes only projects that appear in it. By default, `list` is all the open projects, but it can be restricted to only projects specified in `x`.

What is the use of this, given that the projects to be closed are specified in the right argument? 

If none, make `x` simply a flag, as described in the function header comments.

**Comment by aplteam** [comment]
Fixed in 0.46.0

**Comment by 5jt** [comment]
So, to be clear, the API documentation on preview at

https://lambenttechnology.com/wireframes/cider.dev/api/#close-project

is correct?

**Comment by aplteam** [comment]
Regarding the check, yes, it is, although I expect the number of checks to
increase over time, and that could be reflected somehow. Maybe "For example"

In version 0.46.0 the left argument will be named "performChecks" rather
than x, because removed the other options as suggested by you.

Maybe

   - projects is one or more open projects

should be something like this:

   - projects is one or more open projects or an empty vector for all
   projects currently opened
   ?

**Comment by 5jt** [comment]
Love it. Made and committed the change on main and pushed to my GH fork. Website updated automatically! Commit is included in my pending PR on aplteam/Cider. Beautiful. 
￼
