### ISSUE TITLE
Unable to open CIDER project

### ISSUE THREAD

**Issue by KarlTD** [aplteam/Cider#20]
I got the following issue

1.	`]cd` to some project folder
2.	`]CIDER.CreateProject`
a.	Accept default `cider.config`
3.	Open project with `{}⎕SE.UCMD'CIDER.OpenProject .'

Result:

`Invalid LINK parameter: info_url`
`CheckParameters[9] ('Invalid LINK parameter',((1<+/~bool)/'s'),': ',{0=≢⍵:'' ⋄ ⊃{⍺,',',⍵}/⍵}(~bool)/list2)Assert∧/bool`

Workaround:

`GetValidCiderParams` sets `'project_url'` as a valid param but `]CIDER.CreateProject` creates a `cider.config` with a key `info_url`. Replace `info_url` with `project_url` in cider.config solves this issue.

Interpreter:
  Version: 18.2.46765
  Platform: Linux-64
  Edition: Unicode/64

Cider:
  Version: 0.23.6+367

Regards,
Karl

**Comment by aplteam** [comment]
That's a mystery: the new config file derives from the file `cider.config.template` in the `/home/<username>/MyUCMDs/Cider/aplteam-Cider-0.23.6/` folder, and that does not carry `info_url` anymore (`info_url` was renamed to `project_url`).

Do you really see `info_url` when the default config file is presented to you in an edit window?

Please provide your email address or send an email to kai@aplteam.com because I also want to discuss something unrelated.

**Comment by KarlTD** [comment]
I made a mistake; I had a previous version of Cider in MyUCMDs that clashed with the new version installed by tatin. I created a project using an old version and loaded it using docker with the latest version. My apologies.
