### ISSUE TITLE
Consider replacing [ and ] by < and > for marking up aliases

### ISSUE THREAD

**Issue by 5jt** [aplteam/Cider#95]
Expected same results for aliases and file paths.

Actual results:

```
      ]CIDER.ListAliases
 bar  /Users/sjt/tmp/foo 
      ]CIDER.ListNuGetDependencies /Users/sjt/tmp/foo
No dependencies found
      ]CIDER.ListNuGetDependencies bar
* Command Execution Failed: No Cider config file found
      ]CIDER.ListTatinDependencies bar
* Command Execution Failed: Right argument is not a directory
      ]CIDER.OpenProject bar
* Command Execution Failed: Folder does not exist: bar
      ]CIDER.ListOpenProjects
 Namespace name  Path 
 --------------  ---- 
      ]CIDER.OpenProject /Users/sjt/tmp/foo
The current directory is now /Users/sjt/tmp/foo
Project successfully opened and established in "#.foo"

      ]CIDER.ListOpenProjects
 Namespace name  Path               
 --------------  ----               
 #.foo           /Users/sjt/tmp/foo 
```

**Comment by aplteam** [comment]
Aliases are aliases when embraced by `[]`, so

```
]CIDER.OpenProject [bar]
```

will work.

**Comment by 5jt** [comment]
Should also be clearer in the User Commands documentation – on it.

**Comment by 5jt** [comment]
When I create an alias I don’t specify the square brackets, e.g. 

    ]CIDER.CreateProject path/to/foo bar

so I propose `bar` is the alias and the square brackets are syntax to indicate an alias an not a file path. 

Is it also the case for API functions that a project can be identified by an alias as an alternative to a file path? (Presumably as a string with the square-bracket syntax.)

**Comment by aplteam** [comment]
No, an alias must be defined with `-alias=`. 

The statement 

```
]CIDER.CreateProject path/to/foo bar
```

expects a namespace `bar`.

Aliases are user commands-only. The API functions don't allow aliases.

**Comment by 5jt** [comment]
So the following references to aliases are wrong?

https://github.com/aplteam/Cider/blob/main/docs/Cider-API-Reference.md#addnugetdependencies

https://github.com/aplteam/Cider/blob/main/docs/Cider-API-Reference.md#addtatindependencies

https://github.com/aplteam/Cider/blob/main/docs/Cider-API-Reference.md#folder-mandatory

Also, which is correct? – 

1.  `⎕SE.Cider.DropAlias 'foo'`
1.  `⎕SE.Cider.DropAlias '[foo]'`

Unless only (2) is correct, the square brackets are syntax rather than part of the alias itself. 

My recommendation: treat the square brackets as syntax, not part of the alias itself. (You could then allow `DropAlias` to accept an alias with or without the brackets.) Why? With or without the brackets, the alias above is pronounced *foo*. The brackets *look* like syntax. It’s easier to remember that an alias must be bracketed (to distinguish it from a file path) than that *foo* is actually *left-bracket-foo-right-bracket*.

Please reconsider whether this is an enhancement request or a Docs issue and whether it is closed.

**PS** It’s unfortunate that the syntax definitions for the user commands and API functions (must) follow the convention of using square brackets to mark optional arguments. Would you consider an alternative for marking aliases, e.g. stiles or angle brackets?

**Comment by aplteam** [comment]
Sorry, I confused things. Aliases should be supported by user commands as well as API functions. 

(Some user commands allow something like `[comm*]` as argument, or `[?]`. That might result in the need to communicate with the user, and that's allowed for user commands but forbidden for API functions)

`⎕SE.Cider.DropAlias 'foo'` is correct. There is no need to tell `DropAlias` that the argument is an alias, because nothing else is allowed. Accepting `[foo]` anyway seems wrong because it might muddy the waters. And yes, it's syntax. 

Now I am not so sure anymore whether it's a good idea to let `ListAliases` return the aliases embraced by `[]`...

I usually use `<>` for stuff like `C:\Users\<⎕AN>`, and I am not sure whether this is true for Cider AND Tatin. However, I agree that it is unfortunate that `[]` is commonly used for marking up optional arguments, and indeed, the user command framework leaves us no choice.

We have to keep in mind that this also affects Tatin, because Registries can be addressed by a URL or by alias, like `[tatin]` for the principal one. I don't know what stiles are - do you mean `||`?

**Comment by aplteam** [comment]
`ListAlias`: it's not a good idea because it makes it unclear whether the brackets are part of the alias as such. It fights one confusion by creating another one.
